language: node_js
node_js:
  - "8.6.0"
  - "node"
install:
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test:unit
        - npm run test:e2e -- --headless
